# Generated by Django 2.2.2 on 2019-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('webSite', models.CharField(max_length=100)),
                ('logoPath', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
